[project]
name = "tinymoa"
version = "0.1.0"

[build]
sources = ["hardware/rtl"]
target = {type = "directory", path = "hardware/target"}
# sourcemap_target = {type = "directory", path = "[dst dir]"}
sourcemap_target = {type = "none"}
incremental = false # only re-compile outdated files
exclude_std = false

[test]
simulator = "verilator"
waveform_format = "fst"
